### ISSUE TITLE
Token resource endpoint address should be configurable

### ISSUE THREAD

**Issue by IlianSchokkaert** [infrabel/themes-gnap#121] opened 2015-03-04 08:17 UTC
The GNAP jwt token issuer sets the default api path to /tokens. The client side token.resource uses the path /api/tokens resulting in a post error.

Since the issuer path can be changed server side via the properties => settings menu, it should also be configurable client side

<b>Server side</b>
GNaP.Owin.Authentication.Jwt/src/GNaP.Owin.Authentication.Jwt/JwtTokenIssuerOptions.cs
```
public class JwtTokenIssuerOptions
{
    private const string DefaultIssuerPath = "/tokens";
```

<b>Client side</b>
themes-gnap/custom/gnap-angular/js/develop/gnap/token.resource.js 
```
function Token($resource) {
    return $resource('/api/tokens');
}
```

**Comment by CumpsD** [comment] 2015-03-04 08:57
Duplicate of https://github.com/infrabel/themes-gnap/issues/92

**Closed by CumpsD** 2015-03-04 08:57 UTC
Labels: duplicate
